PurpleBuzzTask/Models/Service.cs
using PurpleBuzzTask.Areas.Dashboard.Models;

namespace PurpleBuzzTask.Models
{
    public class Service:BaseAuditableEntity
    {
        
        public string Title { get; set; }

        public string Description { get; set; }
        public string MainImageUrl { get; set; }
        public ICollection<Work> Works { get; set; }

    }
}

PurpleBuzzTask/Areas/Admin/Controllers/ServiceController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using PurpleBuzzTask.DAL;
using PurpleBuzzTask.DTOs;
using PurpleBuzzTask.Models;
using PurpleBuzzTask.Services.Concretes;
using PurpleBuzzTask.Services.Interfaces;
using PurpleBuzzTask.Utilities;
using System.Runtime.CompilerServices;

namespace PurpleBuzzTask.Areas.Admin.Controllers
{
    [Area("Admin")]

    public class ServiceController : Controller
    {
        private readonly AppDbContext _context;
        private readonly IServiceForService _service;
        private readonly IWebHostEnvironment _webHostEnvironment;
        public ServiceController(IWebHostEnvironment webHostEnvironment, IServiceForService service, AppDbContext context)
        {

            _webHostEnvironment = webHostEnvironment;
            _service = service;
            _context = context;
        }
        public async Task<IActionResult> Index()
        {
            IEnumerable<Service> services = await _context.Services.Include(a => a.Works).ToListAsync();

            return View(services);
        }
        public IActionResult Delete(int id)
        {
            var result = _context.Works.Any(x => x.ServiceId == id);
            if (result)
            {
                return BadRequest("Something went wrong");
            }
            Service? deletedService = _context.Services.Find(id);
            if (deletedService == null) {
                return NotFound();
            }
            else
            {
                _context.Services.Remove(deletedService);
                try
                {
                    _context.SaveChanges();
                }
                catch (Exception ex)
                {

                    return StatusCode(404, "something is wrong");
                }
            }
            return View();
        }
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Create(ServiceDto serviceDto)
        {
            if (!ModelState.IsValid)
            {

                return View(serviceDto);
            }
            if (!serviceDto.Img.CheckType())
            {
                ModelState.AddModelError("img", "image formati olmalidir");
                return View(serviceDto);
            }
            if (!serviceDto.Img.CheckSize(2))
            {
                ModelState.AddModelError("img", "2mbytdan kicik olmalidir");
                return View(serviceDto);
            }
            Service service = new Service
            {
                CreatedAt = DateTime.Now,
                Description = serviceDto.Description,
                MainImageUrl = serviceDto.Img.UploadImage(_webHostEnvironment.WebRootPath, "test"),
                Title = serviceDto.Title
            };
            _service.CreateService(service);


            return RedirectToAction(nameof(Index));

        }


    }

}

PurpleBuzzTask/Areas/Admin/Views/Service/Create.cshtml
@model ServiceDto;
<form method="post" enctype="multipart/form-data">
    <div class="mb-3 row">
        <label for="staticEmail" asp-for="Title" class="col-sm-2 col-form-label">Title</label>
        <div class="col-sm-10">
            <input  asp-for="Title" class="form-control" id="staticEmail" >
        </div>
        <span class="text-danger" asp-validation-for="Title"></span>
    </div>
  
    <div class="mb-3 row">
        <label for="inputPassword" asp-for="Description" class="col-sm-2 col-form-label">Description</label>
        <div class="col-sm-10">
            <input asp-for="Description" class="form-control" id="inputPassword">
        </div>
        <span class="text-danger" asp-validation-for="Description"></span>
    </div>
    <div class="mb-3 row">
 
        <input class="form-control"asp-for="Img" id="formFile">
        <span class="text-danger" asp-validation-for="Img"></span>
    </div>
 
    
    <button type="submit">Submit</button>
</form>

PurpleBuzzTask/Areas/Admin/Views/Service/Delete.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

PurpleBuzzTask/Areas/Admin/Views/Service/Index.cshtml
@model IEnumerable<Service>;

<a class=" mb-2 btn btn-primary " asp-controller="Service" asp-action="Create" type="submit">Create</a>
<table class="table table-dark">
    <thead>
        <tr>
            <th scope="col">Id</th>
            <th scope="col">Title</th>
            <th scope="col">Description</th>
            <th scope="col">Img</th>
            <th scope="col">WorkId</th>
            <th scope="col">Actions</th>
        </tr>
    </thead>
    <tbody>
        @foreach (Service item in Model)
        {
            <tr>
                <th scope="row">@item.Id</th>
                <td>@item.Title</td>
                <td>@item.Description</td>
                <td><img width="100" height="60" src="~/test/@item.MainImageUrl" /></td>
                <td>
                    @foreach (var work in item.Works)
                    {
                    <p>@work.Id</p>
                    }
                </td>
                
              
               
                <td>
                    <a class=" btn btn-primary " asp-action="Update" asp-route-Id="@item.Id" type="submit">Update</a>
                    <a class=" btn btn-primary " asp-action="Delete" asp-route-Id="@item.Id" type="submit">Delete</a>
                </td>


            </tr>
        }


    </tbody>
</table> 

PurpleBuzzTask/Areas/Admin/Views/Service/Update.cshtml
@using PurpleBuzzTask.Models;
@model Service;

<form method="post">
    <div class="mb-3 row">
        <label for="staticEmail" asp-for="Title" class="col-sm-2 col-form-label">Title</label>
        <div class="col-sm-10">
            <input type="text" asp-for="Title" class="form-control-plaintext" id="staticEmail" >
        </div>
    </div>
    <div class="mb-3 row">
        <label for="inputPassword" asp-for="Description" class="col-sm-2 col-form-label">Description</label>
        <div class="col-sm-10">
            <input asp-for="Description" class="form-control" id="inputPassword">
        </div>
    </div>
    <div class="mb-3 row">
        <label asp-for="MainImageUrl" class="col-sm-2 col-form-label">img url</label>
        <div class="col-sm-10">
            <input asp-for="MainImageUrl" class="form-control" id="inputPassword">
        </div>
    </div>
    <button type="submit">Submit</button>
</form>